package ps.wakeel.phone.design

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Every colour of the product, exactly as `design/tokens.json` exports them from the Pen
 * file. The names are the token names, so a screen never invents a colour: it asks for the
 * token the design named.
 */
@Immutable
data class WakeelColors(
    val bg: Color,
    val surface: Color,
    val surface2: Color,
    val border: Color,
    val borderStrong: Color,
    val text: Color,
    val muted: Color,
    val placeholder: Color,
    val primary: Color,
    val primaryHover: Color,
    val primaryPressed: Color,
    val primarySoft: Color,
    val primaryBorder: Color,
    val primaryFill: Color,
    val success: Color,
    val successSoft: Color,
    val successBorder: Color,
    val successFill: Color,
    val warning: Color,
    val warningSoft: Color,
    val warningBorder: Color,
    val warningFill: Color,
    val danger: Color,
    val dangerSoft: Color,
    val dangerBorder: Color,
    val dangerFill: Color,
    val info: Color,
    val infoSoft: Color,
    val infoBorder: Color,
    val infoFill: Color,
    val neutralSoft: Color,
    val disabled: Color,
    val disabledBg: Color,
    val sidebar: Color,
    val sidebarHover: Color,
    val sidebarSelected: Color,
    val sidebarText: Color,
    val sidebarMuted: Color,
    val sidebarDivider: Color,
    val tableHeader: Color,
    val attentionBg: Color,
    val scrim: Color,
    val white: Color,
    val onFill: Color,
    val isDark: Boolean,
)

internal val WakeelLightColors = WakeelColors(
    bg = Color(0xFFF3F4F6),
    surface = Color(0xFFFFFFFF),
    surface2 = Color(0xFFF7F8F9),
    border = Color(0xFFD5D9DE),
    borderStrong = Color(0xFFB9C0C7),
    text = Color(0xFF1D272D),
    muted = Color(0xFF66737B),
    placeholder = Color(0xFF8C979E),
    primary = Color(0xFF2D6F66),
    primaryHover = Color(0xFF367D73),
    primaryPressed = Color(0xFF245A53),
    primarySoft = Color(0xFFE7F1EF),
    primaryBorder = Color(0xFFB9D7D1),
    primaryFill = Color(0xFF2D6F66),
    success = Color(0xFF31735D),
    successSoft = Color(0xFFEAF5F0),
    successBorder = Color(0xFFA7CFBE),
    successFill = Color(0xFF31735D),
    warning = Color(0xFFA06B18),
    warningSoft = Color(0xFFFFF6E5),
    warningBorder = Color(0xFFE8C982),
    warningFill = Color(0xFFA06B18),
    danger = Color(0xFFA43E43),
    dangerSoft = Color(0xFFFCEBED),
    dangerBorder = Color(0xFFE6AEB2),
    dangerFill = Color(0xFFA43E43),
    info = Color(0xFF3E6D8C),
    infoSoft = Color(0xFFEDF4F7),
    infoBorder = Color(0xFFBCD1DC),
    infoFill = Color(0xFF3E6D8C),
    neutralSoft = Color(0xFFEAEDF0),
    disabled = Color(0xFFA7AFB5),
    disabledBg = Color(0xFFE5E7E9),
    sidebar = Color(0xFF1D2B32),
    sidebarHover = Color(0xFF263941),
    sidebarSelected = Color(0xFF304B52),
    sidebarText = Color(0xFFD5DDE0),
    sidebarMuted = Color(0xFFAEBBC1),
    sidebarDivider = Color(0xFF38505A),
    tableHeader = Color(0xFFE9ECEF),
    attentionBg = Color(0xFFFFF9ED),
    scrim = Color(0x991D272D),
    white = Color(0xFFFFFFFF),
    onFill = Color(0xFFFFFFFF),
    isDark = false,
)

internal val WakeelDarkColors = WakeelColors(
    bg = Color(0xFF121A1E),
    surface = Color(0xFF1A252B),
    surface2 = Color(0xFF202D34),
    border = Color(0xFF2E3D45),
    borderStrong = Color(0xFF3C4D56),
    text = Color(0xFFE6ECEF),
    muted = Color(0xFF9AAAB2),
    placeholder = Color(0xFF728089),
    primary = Color(0xFF7FD0C2),
    primaryHover = Color(0xFF38897E),
    primaryPressed = Color(0xFF266A61),
    primarySoft = Color(0xFF1F3B38),
    primaryBorder = Color(0xFF2E5551),
    primaryFill = Color(0xFF2F7A70),
    success = Color(0xFF7CCBA4),
    successSoft = Color(0xFF1E3A30),
    successBorder = Color(0xFF2E5A47),
    successFill = Color(0xFF2E7D5B),
    warning = Color(0xFFE3B45C),
    warningSoft = Color(0xFF3A2E14),
    warningBorder = Color(0xFF6A5220),
    warningFill = Color(0xFF8A5E14),
    danger = Color(0xFFEE8E93),
    dangerSoft = Color(0xFF3D2224),
    dangerBorder = Color(0xFF6B3237),
    dangerFill = Color(0xFFB4484E),
    info = Color(0xFF8CBBDA),
    infoSoft = Color(0xFF1F3140),
    infoBorder = Color(0xFF2F4D62),
    infoFill = Color(0xFF3E6D8C),
    neutralSoft = Color(0xFF263238),
    disabled = Color(0xFF5C6A72),
    disabledBg = Color(0xFF2A363D),
    sidebar = Color(0xFF0E1519),
    sidebarHover = Color(0xFF182228),
    sidebarSelected = Color(0xFF24333B),
    sidebarText = Color(0xFFC9D3D8),
    sidebarMuted = Color(0xFF7F8F97),
    sidebarDivider = Color(0xFF26343B),
    tableHeader = Color(0xFF1F2B31),
    attentionBg = Color(0xFF33291A),
    scrim = Color(0xA6000000),
    white = Color(0xFFFFFFFF),
    onFill = Color(0xFFFFFFFF),
    isDark = true,
)
