namespace Wakeel.Crypto;

/// <summary>The three working roles a computer account can carry.</summary>
public static class SetupRoles
{
    public const string Manager = "manager";
    public const string Secretary = "secretary";
    public const string Custodian = "custodian";

    public static bool IsKnown(string? role) =>
        role is Manager or Secretary or Custodian;
}

/// <summary>How much of the office's work a device is allowed to receive.</summary>
public static class SetupSyncScopes
{
    /// <summary>Everything the office holds: the manager and the secretary.</summary>
    public const string Full = "full";

    /// <summary>Only the custody records: the custodian's own device.</summary>
    public const string Custody = "custody";

    public static bool IsKnown(string? scope) => scope is Full or Custody;
}

/// <summary>The names the five entries of a setup file always carry.</summary>
public static class SetupEntryNames
{
    public const string Content = "setup.json";
    public const string Logo = "logo.png";
    public const string Guide = "guide.pdf";
    public const string ReportTemplate = "report-template.docx";

    /// <summary>
    /// The official correspondence template, written and read exactly like
    /// <see cref="ReportTemplate"/> (AGREEMENT item 57 / ARCHITECTURE §4).
    /// </summary>
    public const string LetterTemplate = "letter-template.docx";
}

/// <summary>
/// The organisation as the setup file describes it: its identity, the two public keys the
/// whole trust model hangs from, and the two settings that only the administrator may decide.
/// </summary>
public sealed record SetupOrg(
    string Id,
    string Name,
    string SigningPub,
    string X25519Pub,
    int CycleStartDay,
    string NumberingFormat)
{
    /// <summary>Lowest and highest day of the month a financial cycle may start on.</summary>
    public const int MinCycleStartDay = 1;

    public const int MaxCycleStartDay = 28;
}

/// <summary>
/// One node of the four level structure: organisation, department, section, unit.
/// A node that hosts an office also carries the office code used by the inventory.
/// </summary>
public sealed record SetupUnit(
    string Id,
    string? ParentId,
    int Level,
    string Name,
    string? HeadTitle,
    string? HeadName,
    string? OfficeCode)
{
    public const int TopLevel = 1;

    public const int DeepestLevel = 4;
}

/// <summary>The office this installation belongs to: a node of the structure and its code.</summary>
public sealed record SetupOffice(string UnitId, string OfficeCode);

/// <summary>
/// The computer account this file activates, with the certificate the organisation issued it.
/// The private seeds travel separately in <see cref="SetupContent.DeviceSeed"/>.
/// </summary>
public sealed record SetupDevice(
    string Id,
    int DeviceNo,
    string Role,
    string SyncScope,
    DeviceCertificate Certificate)
{
    public const int MinDeviceNo = 1;

    public const int MaxDeviceNo = 9;
}

/// <summary>The person who will work on this installation.</summary>
public sealed record SetupEmployee(string Name, int EmployeeNo, string JobTitle)
{
    public const int MinEmployeeNo = 1;

    public const int MaxEmployeeNo = 9;
}

/// <summary>
/// Which of the four optional entries the administrator chose to put in the file. It is
/// declared rather than inferred, so a stripped entry is a mismatch the reader reports
/// instead of a file that quietly arrives without a logo.
/// </summary>
public sealed record SetupIncludes(bool Logo, bool Guide, bool ReportTemplate, bool LetterTemplate)
{
    public static SetupIncludes None { get; } = new(false, false, false, false);
}

/// <summary>
/// <c>setup.json</c>: everything an installation needs to exist, written canonically and
/// carried inside the encrypted payload of a <see cref="ContainerKind.Setup"/> container.
/// Two of its fields are secrets and owe their protection entirely to that payload:
/// <see cref="DeviceSeed"/> and <see cref="OfficeKey"/>.
/// </summary>
public sealed record SetupContent(
    int FormatVersion,
    DateTimeOffset ExportedAt,

    // Rises by one with every file the administrator exports for this device, so an
    // installation can refuse a file older than the one it already applied.
    long ExportSeq,
    SetupOrg Org,
    IReadOnlyList<SetupUnit> Units,
    SetupOffice Office,
    SetupDevice Device,

    // The device's own private key seeds. They are generated by the administration tool,
    // handed over exactly once here, and deleted there after the first export.
    DeviceSeeds DeviceSeed,
    SetupEmployee Employee,

    // The office key, base64url, thirty two bytes.
    string OfficeKey,
    RevocationList? Revocation,
    SetupIncludes Includes)
{
    /// <summary>The only format version this build writes and reads.</summary>
    public const int CurrentFormatVersion = 1;

    /// <summary>Length in bytes of the office key.</summary>
    public const int OfficeKeySize = 32;

    /// <summary>The canonical bytes stored as <c>setup.json</c>.</summary>
    public byte[] ToCanonicalBytes() => CanonicalJson.SerializeToUtf8Bytes(this);

    /// <summary>Reads <c>setup.json</c> back. Anything unreadable is damage, never a bug.</summary>
    public static SetupContent Parse(ReadOnlySpan<byte> utf8Json)
    {
        var content = CanonicalJson.Deserialize<SetupContent>(utf8Json);

        // A hostile or truncated document deserialises into a record whose non nullable
        // members are simply null; every later check reads them, so the shape is settled here.
        if (content.Org is null
            || content.Units is null
            || content.Office is null
            || content.Device is null
            || content.DeviceSeed is null
            || content.Employee is null
            || content.Includes is null)
        {
            throw new CryptoException(ErrorCode.Corrupt, "The setup description is missing one of its parts.");
        }

        return content;
    }

    /// <summary>The office key bytes, or an empty array when the field is unreadable.</summary>
    public bool TryGetOfficeKey(out byte[] officeKey)
    {
        if (Base64Url.TryDecode(OfficeKey, out var bytes) && bytes.Length == OfficeKeySize)
        {
            officeKey = bytes;
            return true;
        }

        officeKey = [];
        return false;
    }

    /// <summary>The unit that hosts this installation's office, when the structure names one.</summary>
    public SetupUnit? OfficeUnit() =>
        Units?.FirstOrDefault(unit =>
            unit is not null && string.Equals(unit.Id, Office?.UnitId, StringComparison.Ordinal));
}

/// <summary>
/// Everything about a setup file that is safe to show before the file has passed every
/// check — the organisation, the structure, the office, the device, the employee and which
/// optional entries the file claims to carry. This is what W03 renders next to the check
/// list even for a file a later item refuses (another device, an older export, a revoked
/// device): a person can still be told whose file this is. Deliberately excludes
/// <see cref="SetupContent.DeviceSeed"/> and <see cref="SetupContent.OfficeKey"/> — the two
/// secrets the payload actually carries — and the revocation list, which is judged, never
/// displayed. <see cref="SetupPackage.Content"/> carries the full record, gated behind the
/// checks passing.
/// </summary>
public sealed record SetupDescription(
    int FormatVersion,
    DateTimeOffset ExportedAt,
    long ExportSeq,
    SetupOrg Org,
    IReadOnlyList<SetupUnit> Units,
    SetupOffice Office,
    SetupDevice Device,
    SetupEmployee Employee,
    SetupIncludes Includes)
{
    internal static SetupDescription From(SetupContent content) => new(
        content.FormatVersion,
        content.ExportedAt,
        content.ExportSeq,
        content.Org,
        content.Units,
        content.Office,
        content.Device,
        content.Employee,
        content.Includes);
}
